### ISSUE TITLE
the files in the dropbox link are deleted for the creation of seseg files ?

### ISSUE THREAD

**Issue by Eisorak** [ranahanocka/MeshCNN#100]
Hello,

the files in the dropbox link are deleted for the creation of seseg files ?

**Comment by ranahanocka** [comment]
Hi @Eisorak --

Whoops -- looks like Dropbox accidentally deleted this in a sync.
Thanks for letting me know -- I recovered the files and updated the link in the wiki so it should work now.

**Comment by Eisorak** [comment]
Hi @ranahanocka 

thank you very much.
