### ISSUE TITLE
run the project under windows

### ISSUE THREAD

**Issue by Eisorak** [ranahanocka/MeshCNN#101]
Hi @ranahanocka 

I wanted to run your project on a linux virtual machine but I can't because it doesn't recognize my graphic card, so I want to run it on windows but the execution codes are in shell (train.sh, test.sh,...).

Can you offer me a solution please?

thanks

**Comment by ranahanocka** [comment]
Hi @Eisorak ,

I think Docker is better than a VM.

In any case, the .sh files is just a single python command to run the train/test. So running the python command directly should work in any platform.

**Comment by Eisorak** [comment]
Hi @ranahanocka 

what do you mean by direct execution of the python command, because when I execute the train.py it asks me for the --dataroot,.....
can you give me an example of the command to execute on windows please?

**Comment by Eisorak** [comment]
I managed to solve the problem, it was enough to execute the python command train.py with all the arguments of train.sh on the same line.

thanks
