### ISSUE TITLE
How to get final segmentation plots?

### ISSUE THREAD

**Issue by fatemehteimury** [ranahanocka/MeshCNN#11]
Hi Rana, 
I really appreciate you for sharing such a nice code and your mesh pooling idea is really great. 
I used your segmentation code for my own dataset and I expected to get a vector that represents which edge belongs to which segment or final segmentation plot you provide in the Github. 

Besides, what I get is in the checkpoints, human seg I get some obj files that shows how mesh-pool decimate faces (gray plots you provide in the Github which I can see through view.sh) I supposed these plots should be allocated to classification. 
It would be so nice if you help me to find my answer. 

Best regards, 
Fatemeh

**Comment by ranahanocka** [comment]
Hi @fatemehteimury ,

Thanks for the kind words :+1: 

Did you try running the example for segmentation? I just re-ran it, exactly as I wrote in the wiki:
```
bash ./scripts/human_seg/get_data.sh
bash ./scripts/human_seg/train.sh
bash ./scripts/human_seg/get_pretrained.sh
bash ./scripts/human_seg/test.sh
bash ./scripts/human_seg/view.sh
```
 and when I run view.sh I get this
![image](https://user-images.githubusercontent.com/14359648/62653590-80c97580-b966-11e9-9b14-5379f1c04664.png)

Basically, what happened here, is when you run test.py, it calls the test method in mesh_classifier.py , which runs the forward pass on the network and then exports the segmentation IDs per edge by writing the lines out in the test .obj files (see [this line](https://github.com/ranahanocka/MeshCNN/blob/master/models/mesh_classifier.py#L114)).

So after you ran test, when you pass this .obj to the viewer, it will plot the predicted edge segmentation colors.

**Comment by fatemehteimury** [comment]
Dear Rana, 
Thanks for your kind response. 
Best regards, 
Fatemeh
