### ISSUE TITLE
cannot install pytorch=1.2.0

### ISSUE THREAD

**Issue by kimhkyung0316** [ranahanocka/MeshCNN#149]
I used both M1 mac and windows laptop with anaconda.
In both case, I was unable to install pytorch=1.2.0

![image (1)](https://user-images.githubusercontent.com/36398403/226305816-b360fd39-b425-4b3e-8a4f-42c0f46e7175.png)

For now, there are a lot of newer versions of pytorch. Should I only use pytorch 1.2.0 to run the model?

**Comment by kimhkyung0316** [comment]
recent version of pytorch works well.

**Comment by Peng817** [comment]
> recent version of pytorch works well.

I'm also having trouble in installing cuda 1.2.0, and I want know what is the cuda version you were working on ?
