### ISSUE TITLE
During the training time, the samples have the same adjacent-edge matrix?

### ISSUE THREAD

**Issue by dclcs** [ranahanocka/MeshCNN#19]
Hi Rana,
My task is to use MeshCNN generate some specific meshes. 
I have same questions during using this.During the training time, the samples have the same adjacent-edges matrix? Meshes in my dataset have different , can I use MeshCNN?

**Comment by ranahanocka** [comment]
I am not sure I understand your question.
What is adjacent-edges matrix? What exactly is your task?
Currently this code only supports classification & segmentation.

**Comment by ranahanocka** [comment]
Hi @dclcs ,

I am closing this issue , as I haven't heard from you. If you still need further clarification - let me know.
