### ISSUE TITLE
how to get mean & std for edge features?

### ISSUE THREAD

**Issue by TerenceCYJ** [ranahanocka/MeshCNN#20]
Hi @ranahanocka 
In` __getitem__()`
`meta['edge_features'] = (edge_features - self.mean) / self.std`
Which self.mean and self.std are read from 'mean_std_cache.p' file.

How to get such file? How to implement it in my own data without such file?

Thanks

**Comment by ranahanocka** [comment]
If it doesn't exist, it is calculated automatically from the training data. Please organize your data in the same way that I organized it in the example sets, and delete the `mean_std_cache.p`, and re-run the code.

**Comment by TerenceCYJ** [comment]
Hi @ranahanocka ,
Why do you use mean and std here? If it is used for normalization, why do you use the mean and std of features from all samples?

Thanks

**Comment by ranahanocka** [comment]
@TerenceCYJ It is common practice in machine learning to do something called "input feature normalization", where the distribution of all features in the set is normalized to have mean zero and standard deviation 1. For an explanation, see [here](https://www.youtube.com/watch?v=e1nTgoDI_m8).

**Comment by TerenceCYJ** [comment]
Sure, thank you very much! @ranahanocka
