### ISSUE TITLE
The environment requires Pytorch with CUDA

### ISSUE THREAD

**Issue by hagar-dolev** [ranahanocka/MeshCNN#21]
Hey,

I have installed Pytorch without CUDA (since I don't have a NVIDIA gpu) and it raises an error that requires mending your code.
`AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`

It might be worth mentioning in the Readme file.

It fails at:

`MeshCNN/options/base_options.py", line 54, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
`

I have tried changing it locally to work but it seems like it leads to more errors relating that.
The issue is, since I can't use CUDA, which pytorch version should I install? (As I installed "CUDAless" version).

Thanks!

**Comment by ranahanocka** [comment]
Use the flag `--gpu_ids -1`

It is defined in this line in [base_options.py](https://github.com/ranahanocka/MeshCNN/blob/cf93099bb1de4b5fbd9c18e6241af298b839af06/options/base_options.py#L30)
