### ISSUE TITLE
torch.BoolTensor is supported since torch >= 1.2.0

### ISSUE THREAD

**Issue by ycjungSubhuman** [ranahanocka/MeshCNN#25]
Hi, first of all, thanks for sharing this code public!

I've discovered a problem with the README. It says it works with pytorch 1.0, but it won't because it is using `torch.BoolTensor` in `model/layers/mesh.py`. `torch.BoolTensor` is supported since 1.2.0.

I confirmed the test code for `scripts/human_seg` is working fine with pytorch 1.2.0. I hope this information helps other guys testing this code.

**Comment by ranahanocka** [comment]
Hi @ycjungSubhuman ,

Thanks , I updated it :)
