### ISSUE TITLE
Unable to reach specified number of pooled edges

### ISSUE THREAD

**Issue by KunalMGupta** [ranahanocka/MeshCNN#26]
I am trying to implement MeshCNN for Shapenet models. While It seems that I am able to get past the manifold issue using https://github.com/hjwdzh/Manifold but I am stuck with another problem. I have noticed that the number of pooled edges vary (maybe because feature vectors are different and therefore they appear differently in the queue each time) and often they are larger than the target number of pooled edges. Do you have any idea as to why this might be happening? Is there a way around this problem?

Thanks!

**Comment by ranahanocka** [comment]
Hi @KunalMGupta ,

Thanks for letting me know. I noticed that the Manifold code often leaves small pyramids "floating", and this is a problem. I wrote about this problem and the fix in [this issue](https://github.com/ranahanocka/MeshCNN/issues/7#issuecomment-519568607). Let me know if that fixes it :)
