### ISSUE TITLE
How to get the Mesh output?

### ISSUE THREAD

**Issue by sawadika213** [ranahanocka/MeshCNN#28]
Thank you for your great work! 
I run your code on my local machine.But I have a little question. I use a Cube Mesh and operate a MeshConv on it , I can get the output features, but how can I get the mesh result? 

![TIM截图20190918172235](https://user-images.githubusercontent.com/53416445/65135788-1c0b3b80-da39-11e9-9120-3b8fa63b5948.png)

and output

![image](https://user-images.githubusercontent.com/53416445/65135867-3e04be00-da39-11e9-8739-fd5c283317f2.png)

**Comment by ranahanocka** [comment]
Not sure what you mean.

Anyway, please start by taking a look at the examples scripts (e.g., for cubes, see the [train](https://github.com/ranahanocka/MeshCNN/blob/master/scripts/cubes/train.sh), [test](https://github.com/ranahanocka/MeshCNN/blob/master/scripts/cubes/test.sh), and [viewer](https://github.com/ranahanocka/MeshCNN/blob/master/scripts/cubes/view.sh)).

**Comment by sawadika213** [comment]
Sorry，

I mean I do a MeshConvlution of a mesh(cube mesh, not dataset...) .

I just get the features but I don't how to get a mesh using  output features.

Thanks for your reply , I'm new about it.

**Comment by ranahanocka** [comment]
Hi @sawadika213 ,

Currently the operation you have done is take some mesh (presumably a cube), and extract the simple geometric features per edge (5-dimensional feature vector). Then you created a mesh convolution layer,  and applied it on the 5-dimensional feature vector and brought it to 2-dimensions. So, all you did was change the edge features. The mesh itself (the topology, the connectivity) stayed the same. If you use meshpooling, then the mesh will change.

I suggest going through the examples in this repo, I have tools for visualizing the results, and I think it will be more clear.

**Comment by sawadika213** [comment]
Exactly, I feel the MeshConv is very different from the convlution on image.I understand it. 

Thank you reply!!
