### ISSUE TITLE
why using obj file as input instead stl files?

### ISSUE THREAD

**Issue by reuvenlivn** [ranahanocka/MeshCNN#31]
hi rana
We at printsyst are using mostly STL files. This is the standard output format of many cad tools and most common format for 3D printers. 
why you used (and using) obj file instead?

Reuven

**Comment by ranahanocka** [comment]
hi @reuvenlivn ,

There is no standard 3D format.

As we discussed over e-mail, you can easily convert to .obj files. Anyway, the problems you are facing with duplicate vertices and zero area faces are not specific to .stl files. Even if the code supported .stl files, you would still need to remove and clean degenerate geometry.

Good luck!
-Rana
