### ISSUE TITLE
how to run   on  cpu   enviroment

### ISSUE THREAD

**Issue by peichenzhong** [ranahanocka/MeshCNN#32]
bash ./scripts/shrec/train.sh
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1549630534704/work/torch/csrc/cuda/Module.cpp line=34 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    opt = TrainOptions().parse()
  File "/home/peichen/python_test/MeshCNN/options/base_options.py", line 54, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/home/peichen/anaconda3/envs/meshcnn/lib/python3.6/site-packages/torch/cuda/__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /opt/conda/conda-bld/pytorch_1549630534704/work/torch/csrc/cuda/Module.cpp:34

**Comment by ankitpatnala** [comment]
add an argument --gpu_ids -1/

**Comment by peichenzhong** [comment]
and    python test.py --gpu_ids -1 --dataroot datasets
Running Test
loaded mean / std from cache
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    run_test()
  File "test.py", line 12, in run_test
    model = create_model(opt)
  File "/home/peichen/python_test/MeshCNN/models/__init__.py", line 3, in create_model
    model = ClassifierModel(opt)
  File "/home/peichen/python_test/MeshCNN/models/mesh_classifier.py", line 33, in __init__
    self.gpu_ids, opt.arch, opt.init_type, opt.init_gain)
  File "/home/peichen/python_test/MeshCNN/models/networks.py", line 102, in define_classifier
    opt.resblocks)
  File "/home/peichen/python_test/MeshCNN/models/networks.py", line 132, in __init__
    norm_args = get_norm_args(norm_layer, self.k[1:])
  File "/home/peichen/python_test/MeshCNN/models/networks.py", line 38, in get_norm_args
    raise NotImplementedError('normalization layer [%s] is not found' % norm_layer.func.__name__)
NotImplementedError: normalization layer [BatchNorm2d] is not found
  



how to deal with it ??thank

**Comment by peichenzhong** [comment]
torch_mask = torch.from_numpy(edges_mask.copy())
TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.

**Comment by ankitpatnala** [comment]
you can convert the type to uint8
I had the same issue as i created the environment from the repo's environment.yml file which has pytorch 1.0 but the current code's dependency is pytorch 1.2.0. So the author recommended me to use the old checkout of this branch which somehow works.

**Comment by peichenzhong** [comment]
so   i should  updata my   pytorch into 1.2.0   ???  i  have a try

**Comment by ankitpatnala** [comment]
i dont know the author suggested me to use the old checkout 

please follow this link:
[](https://github.com/ranahanocka/MeshCNN/issues/30#issuecomment-541486859)

**Comment by peichenzhong** [comment]
thank ,  this project is running   ,but  i have a problem  how to watch the layer  or models  on the tensorboardx???

**Comment by peichenzhong** [comment]
i want to watch the graph  ,what should i do

**Comment by ankitpatnala** [comment]
I never used tensorboard but you can find it's documentation .you can save it on a file and try to open the tensboard logdir on other terminal upon which it will give you a local host IP which you can run in your browser. Before that install tensorboard packages as it is not present in the environment.yml file

**Comment by peichenzhong** [comment]
i hava some problem that  how could i compute  the input edge feature which is a 5-dimensional vector every edge???  Anyway ,  i am confused about  the edage value.

**Comment by peichenzhong** [comment]
> I never used tensorboard but you can find it's documentation .you can save the checkpoints on a file and try to open the tensboard logdir on other terminal upon which it will give you a local host IP which you can run in your browser. Before that install tensorboard packages as it is not present in the environment.yml file

**Comment by peichenzhong** [comment]
i hava some problem that  how could i compute  the input edge feature which is a 5-dimensional vector every edge???  Anyway ,  i am confused about  the edges value.

**Comment by ranahanocka** [comment]
hi @peichenzhong ,

> i hava some problem that how could i compute the input edge feature which is a 5-dimensional vector every edge??? Anyway , i am confused about the edges value.

I don't understand your question. Please go through the examples in this Github and follow the instructions in the README, I think it will clarify most of your problems. Also, you can read through the [Github Issues](https://github.com/ranahanocka/MeshCNN/issues?utf8=%E2%9C%93&q=is%3Aissue), which might also answer some questions.

Thanks & Good luck!
-Rana
