### ISSUE TITLE
 visualization 3d objects

### ISSUE THREAD

**Issue by sw-gong** [ranahanocka/MeshCNN#4]
Hi,

The images regarding visualization of 3d objects in your paper are elgent. Can you talk about how did you draw them?

Thanks.

**Comment by ranahanocka** [comment]
Thanks for the compliment. I used [Blender](https://docs.blender.org/) -- which is free and powerful tool for rendering (and also many other things). Blender is very complex, so I had to watch many tutorials on youtube about lighting, materials, shaders, etc. 

For an easy and not so bad looking solution, I suggest using [MeshLab](http://www.meshlab.net/). Once you import the 3D file, add lighting (ctrl + D), and then click the camera:
![image](https://user-images.githubusercontent.com/14359648/57788953-acaad580-7740-11e9-9755-10161b3463de.png)
The result looks pretty good I think:
![image](https://user-images.githubusercontent.com/14359648/57789080-e4198200-7740-11e9-9894-9b80daa425a7.png)

Hope that helps! Good luck :)
