### ISSUE TITLE
What does sides mean?

### ISSUE THREAD

**Issue by liangqianqian123** [ranahanocka/MeshCNN#42]
I want to know that what does sides (which defined in file 'mesh_prepare.py') stand for? Thank you

**Comment by ranahanocka** [comment]
Hi @liangqianqian123 ,

Did you try reading my explanation from [this issue](https://github.com/ranahanocka/MeshCNN/issues/36#issuecomment-546202689)? Hope it clear.

**Comment by liangqianqian123** [comment]
Thank you very much，I fully understand！




On 11/09/2019 09:11, Rana Hanocka wrote:

Hi @liangqianqian123 ,

Did you try reading my explanation from this issue? Hope it clear.
