### ISSUE TITLE
Blender simplify shapes script "Error: File format is not supported"

### ISSUE THREAD

**Issue by claell** [ranahanocka/MeshCNN#48]
When running the blender script to simplify the shapes, it always gives the following message: `Error: File format is not supported in file 'C:\BatchAnalysis\MeshNetworkInput\0\test\filename.obj'`

However, the .obj file is created and can be opened with FreeCAD for example.

**Comment by ranahanocka** [comment]
Hi @claell ,

Yes I observe the same message. I don't think it's an issue as the script works exactly as expected (as you also noticed)

-Rana

**Comment by claell** [comment]
Alright. Thanks for letting me know. Then this can be ruled out as the cause of my other problems.
