### ISSUE TITLE
classification SHREC for split 10 

### ISSUE THREAD

**Issue by kamran-afzal** [ranahanocka/MeshCNN#51]
hi,
While running for split 10 classification on SHREC do we need to change the batch_size to 10 or there are some other settings? shrec16 has 16 training samples for each class, do we need shrec10 of 10 samples for each class?

Kind regards,
Rana Kamran

**Comment by ranahanocka** [comment]
Hi @kamran-afzal ,

We followed the setup described in (GWCNN)[https://people.csail.mit.edu/jsolomon/assets/GW_for_CNN.pdf] (see Table 1). Shrec10 vs. Shrec16 is the train / test split. Where Shrec16 is 16 examples in the train and 4 in the test, and Shrec10 was 10 / 10. The batch size and all the other settings we used were the same for shrec16 and shrec10. You can just run the code as show here :

https://github.com/ranahanocka/MeshCNN/blob/29c30a4d6dee123cacbb662e3f5666420c0e94c5/scripts/shrec/train.sh#L3-L14

**Comment by kamran-afzal** [comment]
thanks for your kind reply.
