### ISSUE TITLE
zlib.error

### ISSUE THREAD

**Issue by tt-study** [ranahanocka/MeshCNN#55]
The problem is that “zlib.error: Error -3 while decompressing data: invalid block type“  when I run the code, maybe the python version doesn't match with yours?

**Comment by ranahanocka** [comment]
Hi @tt-study ,

Never saw something like that, although a quick google search about this error to some pages with bugs in python 2.7 (which is deprecated).

Which version of python are you using? I suggest installing anaconda environment like I wrote in the README.
