### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.bool_

### ISSUE THREAD

**Issue by tt-study** [ranahanocka/MeshCNN#56]
I have the problem when running the code in the environment meshcnn :
TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.

"mask = np.ones(mesh.edges_count, dtype=np.bool)''
How could I solve this problem? Thank you very much~~

**Comment by ranahanocka** [comment]
Hi @tt-study ,

You are running pytorch which is less than version 1.2. The newest version of the MeshCNN code uses pytorch 1.2, you can install the environment as in the readme.

Alternatively, you can check out an older version of the code which used Pytorch 1.0 (i.e., run git checkout cf93099)
