### ISSUE TITLE
label meaning of human segmentation dataset

### ISSUE THREAD

**Issue by dragonbook** [ranahanocka/MeshCNN#6]
Hi, Rana,

I want to parse the human segmentation dataset, but I cannot find the description of it. Is there any online site or directed document about it? And, How can I understand/parse the .eseg and .seseg label files? 

Thanks!

**Comment by ranahanocka** [comment]
Hi @dragonbook , thanks - good point.

I just created a wiki and added a [page about segmentation](https://github.com/ranahanocka/MeshCNN/wiki/Segmentation). Check it out and let me know if it answers your questions

**Comment by dragonbook** [comment]
Thank you!

**Comment by ranahanocka** [comment]
Closing this. Feel free to re-open if you have more questions
