### ISSUE TITLE
Adjacency information after pooling

### ISSUE THREAD

**Issue by Peon26** [ranahanocka/MeshCNN#67]
Hi @ranahanocka ,
I have a rather basic question, how/where is the mesh passed to the next layer after pooling? In other words, to be able to have another convolution and/or pooling operation, one needs a new adjacency matrix of some sort (e.g. `mesh.edges`), but I have failed to find that in the code, could you please let me know where in your implementation the new adjacency (after pooling) is either taken into account or updated? 
Thank you in advance :)

**Comment by ranahanocka** [comment]
Hi @Peon26 --

Yes, the mesh data-structure is passed to both the mesh_conv and mesh_pooling / mesh_unpooling layers. 

Conv doesn't change the adjacency information, but when we collapse edges in the mesh_pooling layer we modify the mesh data structures inside the mesh_pooling layer. 

You can start by looking around [this line of code](https://github.com/ranahanocka/MeshCNN/blob/5af7b9c39d3e871b052f9c4c4315fb03f5f92992/models/layers/mesh_pool.py#L54) in mesh_pool.

**Comment by Peon26** [comment]
Thank you @ranahanocka
