### ISSUE TITLE
 Edge features

### ISSUE THREAD

**Issue by tt-study** [ranahanocka/MeshCNN#69]
Will edge features（the 5-dimensional vector for every edge: the dihedral angle, two inner angles and two edge-length ratios for each face.） be recalculated due to shape update after each pooling？Thank you and look forward to your answer~~

**Comment by ranahanocka** [comment]
Hi @tt-study ,

The 5-dimensional geometric feature vector is only calculated once as input to the network. 

Just as image-CNNs start with a simple 3-dimensional RGB feature vector as input to the network --which is later abstracted to an N-dimensional feature vector with some "deeper" meaning. 

In the same "spirit" MeshCNN abstracts the simple 5-dimensional geometric features to a N-dimensional deep feature per-edge, which carries some higher-level semantic meaning.

**Comment by tt-study** [comment]
Thank you very much for your answer, while I have one more question :
Is the mesh information input in the second convolution layer the same as the mesh information in the first convolution layer? In other words, does the information of the mesh change because of the convolution operation and the pooling operation? 
In mesh_conv.py the code is : def forward(self, x, mesh)

**Comment by ranahanocka** [comment]
Hi @tt-study ,

Convolution does not change the mesh data-structure, only the features per-edge (i.e., x). Pooling will change the mesh data-structure (i.e., collapse edges) and the edge features.

**Comment by dongx358** [comment]
Hi @ranahanocka, thanks for sharing your nice work.

I have a question relevant to the edge feature calculation.

Is there any reason that you use the function fixed_division(to_div, epsilon) with epsilon=0.1 for the division (in the mesh_prepare.py)?

In the current version, it exists in functions angles_from_faces(mesh, edge_faces, faces), get_opposite_angles(mesh, edge_points, side), and get_ratios(mesh, edge_points, side) followed by clip(-1, 1). The epsilon value of 0.1 is added to all the vectors to be normalized. Also, I think it is not correct to calculate the angle by clipping the cos value in [-1, 1].

Can you give me more information on why you implemented them in this way? Thank you. :)

**Comment by tt-study** [comment]
Thank you very much
