### ISSUE TITLE
Specify the number of epochs

### ISSUE THREAD

**Issue by claell** [ranahanocka/MeshCNN#70]
Currently there does not seem to be an option to specify the number of epochs to use for training. I might look into adding that if I find the time.

**Comment by ranahanocka** [comment]
Hi @claell --

You can specify the # of training iterations by passing:

`--niter 200`
`--niter_decay 1000`
for example.

[see here](https://github.com/ranahanocka/MeshCNN/blob/15b83cc6a4db968baf6cf595df78995a9c2dcee3/options/train_options.py#L14) for more info

**Comment by claell** [comment]
Thanks for the hint! I looked through the options, but did not understand that niter means the number of epochs.

**Comment by claell** [comment]
Apparently I got that wrong. The number of epochs is actually the sum of `niter` and `niter_decay`.
