### ISSUE TITLE
Software used to draw figures

### ISSUE THREAD

**Issue by DandiC** [ranahanocka/MeshCNN#75]
Hi @ranahanocka. The figures in your paper look very good, and I was wondering if you could share what software did you use to come up with them. In particular, I am interested in knowing what software did you use to draw Figure 4 and the figure that visualizes the input features. I know that you have mentioned [here](https://github.com/ranahanocka/MeshCNN/issues/4) that you use Blender to visualize the 3D models, but I am more interested in knowing how to come up with a figure like the ones I mentioned above. Thanks and congratulations again for such a great paper!

**Comment by ranahanocka** [comment]
Hi @DandiC ,

We used a combination of Adobe photoshop & illustrator for the illustration figures
