### ISSUE TITLE
Error when using own dataset

### ISSUE THREAD

**Issue by AhmadObeid** [ranahanocka/MeshCNN#79]
Thanks for the upload. 
I am facing an error when attempting to use my own data for experimentation. 
I made sure to place all files correctly the way you have done in the used dataset shrec_16. 
The error I am getting says:

> Index can't contain negative values

My dataset is the shrec_17 dataset, where I have patches extracted from the different meshes, and I want to classify them. To reproduce the error, I am attaching a zip folder containing examples of these patches. 

[Examples.zip](https://github.com/ranahanocka/MeshCNN/files/4603451/Examples.zip)

Thank you in advance.

**Comment by ranahanocka** [comment]
Hi @AhmadObeid ,

I think you should reduce the amount of pooling (increase the` --pool_res` flag). Right now by default it is: `--pool_res 600 450 300 180 ` for classification. How about 
`--pool_res 600 450 300 210 ` ?
If that doesn't work, what about `--pool_res 600 450 300 270 `.
You can continue to increase the resolution until you find something that works well with your dataset. Also, make sure that set` --ninput_edges` correctly. See the [wiki](https://github.com/ranahanocka/MeshCNN/wiki/Code-Options) for more info.

**Comment by AhmadObeid** [comment]
Hello, thanks for the answer.
Apologies, I should have closed the issue earlier, as I have already found my solution in other closed issues. 
Namely, issues #60 and #18 .
