### ISSUE TITLE
Your resulting figures are very good! How to render the model with edge?

### ISSUE THREAD

**Issue by chatyan** [ranahanocka/MeshCNN#85]
Your resulting figures are very good! How to render the model with edge?

**Comment by ranahanocka** [comment]
Hi @chatyan ,

The paper figures were rendered with blender. There is a script to visualize the mesh with edges in this repo, but I have now started to use [polyscope](https://github.com/nmwsharp/polyscope) for visualization, which is also great for viewing edges ontop of meshes.

**Comment by chatyan** [comment]
Many thanks!
